### PR TITLE
Cosmetic tweaks: mark supported python3 versions, update readme

### PR DESCRIPTION
**Pull request by sanjayankur31**

### CODE REVIEW

**Comment by sanjayankur31** [comment]
@pgleeson : another mostly cosmetic PR :)

**Comment by sanjayankur31** [comment]
Requires https://github.com/aarongarrett/inspyred/pull/22 to be merged for tests to pass

**Comment by sanjayankur31** [comment]
PR merged in inspyred so this should pass now. Can't figure out how to re-run CI without a dummy push, though.

**Comment by pgleeson** [comment]
@sanjayankur31 Thanks, but tests still failing on 2.7... Ditch it?

**Pull request merged**
